<<<<<<< HEAD
name: magic_8_ball
=======
name: dicee
>>>>>>> def00277e08719c983e9d7b3aca6927c38091eb2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
<<<<<<< HEAD
    - images/
=======
  - images/
>>>>>>> def00277e08719c983e9d7b3aca6927c38091eb2
